
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;


[assembly: AssemblyCompany("")]

[assembly: AssemblyCopyright("Copyright ©  2017")]

//
[assembly: AssemblyTrademark("Tradact")]
[assembly: AssemblyCulture("")]

//17.1229.407"

[assembly: AssemblyVersion("3.17.1229.407")]
[assembly: AssemblyFileVersion("3.17.1229.407")]
